import 'package:ecommerse/models/category_model.dart';
import 'package:ecommerse/models/item_model.dart';

class ImageConstant{
  static String searchImage='assets/images/search.png';
  

  //static List<String> names=["All","Bed","Chair","Single Sofa","Table","Sofa Set","Study Table","Book Shelf"];
  static List<CategoryModel> categories=[
    CategoryModel(title: "All", imageUrl:  "https://media.istockphoto.com/id/118192475/photo/gold-star.jpg?s=612x612&w=0&k=20&c=9kyhuZmPzrXQTHIZCeOAQf2uCiXR_yIsQuod7lYlQKw="),
    CategoryModel(title: "Bed", imageUrl:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxEY1Q0rpHvTw8My02xc36eCtjvG9BeVrs32ZSmng7DCJ-q5qrqce4uoTs4xMGaZn9ImE&usqp=CAU"),
    CategoryModel(title: "Chair", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVyZ7WFjKu-43kDKII-Ylfpcy1T68fOr6EAw&usqp=CAU"),
    CategoryModel(title: "Single Sofa", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0mN-BEnQ24QQL32ozqJ_2x8ZzO2l6KIU3ww&usqp=CAU"),
    CategoryModel(title: "Table", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc_CDGlYJLl0iC7IXmkE9ly2rwMobQ2jiq1B5VJ5Q0rNYVlyiYyLtd1NWd_mjNMmoa7Dg&usqp=CAU"),
    CategoryModel(title: "Sofa Set", imageUrl: "https://i0.wp.com/woodwoon.com/wp-content/uploads/2023/02/CSS0014-corner-sofa-l-shape-sofa-set-furniture-store-in-pakistan-woodwoon.webp?fit=1426%2C1024&ssl=1"),
    CategoryModel(title: "Study Table", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIOwtf9wboxiRyQp2d4uEFrAS5YeqIwz_Y0yn5brYdmuklvkQ_l5rH0Yidk363-XPDAr0&usqp=CAU"),
    CategoryModel(title: "Book Shelf", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-6b1sz0r3d1vZQu7sqqFpUt8di1abyaKF6Bl2tKEy4-CfL0A2Y8MWf_GFmPWe_Grbtgw&usqp=CAU")];

  static List<ItemModel> items = [
    ItemModel(name: 'Item 1',price: '\$10.99',img: 'https://m.media-amazon.com/images/I/51RQWvkjeKL.jpg'),
    ItemModel(name: 'Item 2', price: '\$20.99', img: 'https://media.istockphoto.com/id/900257448/photo/wooden-round-table.jpg?s=612x612&w=0&k=20&c=xW86GqjC8IMqoWtAlCejOSuGlR7_YrM8jlBdufCro7Q='),
    ItemModel(name: 'Item 3', price: '\$30.99', img: 'https://habitt.com/cdn/shop/products/beds-furniture-parker-queen-sized-bed-with-sides-32298457235640.jpg?v=1662972267'),
    ItemModel(name: 'Item 4', price: '\$40.99', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRK2ITonF66XPXGSTLH1-wKNhqokQUbI0-_HP0GEoAr3QSWSj61oEkQQLl5_I8FcO79Xx0&usqp=CAU'),
    ItemModel(name: 'Item 5',price: '\$50.99', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGyAoANXTlzgjRyK8qyCkMxHVXt9ZgvLtKaIt7JTuk_VAM-EUQCcep9qpyTTyAfIyhSP8&usqp=CAU'),
    ItemModel(name: 'Item 6', price: '\$60.99', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqOfbjFx49P11Cy5ruuQBNkzIk7IRRBXUAeQ&usqp=CAU'),
    ItemModel(name: 'Item 7',price: '\$70.99',img: 'https://image.shutterstock.com/image-photo/set-teak-wood-table-chairs-260nw-461559985.jpg'),
    ItemModel(name: 'Item 8',price: '\$80.99',img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0lzyrwfnxlknTjJy3soNuC_bkP_bFoRmIGTw4xTqbwuGPQNY6caMASS4b5xOslVlSfLI&usqp=CAU'),
    ItemModel(name: 'Item 9',price: '\$90.99',img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScWOZJHFzeWBqS3NOdi_3n8mNhgFF_IbyHd2g3DEXcUW4ojPLy7dcmfDT9a5IDgZDDx4c&usqp=CAU'),
    ItemModel(name: 'Item 10',price: '\$100.99',img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTOh3JqP9pG1v7t4jADY3R2UPLh1J7jgSp-g&usqp=CAU'),
    ItemModel(name: "sofa set 1", price: "\$1000", img: "https://shop.gkwretail.com/cdn/shop/articles/Sofa_design.jpg?v=1673875085&width=1100"),
    ItemModel(name: "sofa set 2", price: "\$765.9", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRclYTJ5hnMLqzF3Ah6rfAzcyDEabZfpbLpoA&usqp=CAU"),
    ItemModel(name: "sofa set 3", price: "\$43.4", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN-LhGyTbSV2vUKnrLViVQCzLo1N1_O04arA&usqp=CAU"),
    ItemModel(name: "sofa set 4", price: "\$345.56", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQac97KyilTr7wQE4BgIcmneXGtEOad5Zbt9rP6vxdxjkI9S6S2wT5KkneDgs5Pe0gKKY4&usqp=CAU"),
    ItemModel(name: "sofa set 5", price: "\$643.7", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmJmQkjLI5d9mij3K7VR3wSyTaSdOTCBqU7g&usqp=CAU"),
    ItemModel(name: "sofa set 6", price: "\$345.1", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_OQJ6Vl1dXiR6x5bn0jzCJJ1eXgZtkxl5Zg&usqp=CAU"),
    ItemModel(name: "sofa set 7", price: "\$765.55", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRQs8xETKdDw_UnRQxUFg3cq96Q9j6YxzNZA&usqp=CAU"),
    ItemModel(name: "sofa set 8", price: "\$234.98", img: "https://images.sofology.co.uk/c_scale,w_460,q_70,dpr_3,fl_lossy,f_auto/productmedia/lifestyle/sku001032404.jpg"),
    ItemModel(name: "sofa set 9", price: "\$532.66", img: "https://medleyhome.com/cdn/shop/collections/medley-sofas-collection.jpg?v=1673566513&width=2048"),
    ItemModel(name: "Sinfgle sofa 1", price: "\$23.99", img: "https://urbangalleria.com/cdn/shop/products/hester-sofa-set.jpg?v=1664456482"),
    ItemModel(name: "Sinfgle sofa 2", price: "\$12.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFhd3cqiuUS0zdgN8RNkgvy3zXMLj1mSWIdA&usqp=CAU"),
    ItemModel(name: "Sinfgle sofa 3", price: "\$43.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBRH5JsZ23C35nHBQD_ALzErYZGmX9im_f7w&usqp=CAU"),
    ItemModel(name: "Sinfgle sofa 4", price: "\$13.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrUsMEehCr_8P2SxjckpU0XawJsvZK4VDIVA&usqp=CAU"),
    ItemModel(name: "Sinfgle sofa 5", price: "\$18.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_MAJ4uT9QpZ4RBgknoEC4h3bYP35z-T3JIg&usqp=CAU"),
    ItemModel(name: "Sinfgle sofa 6", price: "\$16.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsUxShGRXdk-Sm-ESIWE8UgmjmL9ErkGwAkA&usqp=CAU"),
    ItemModel(name: "Sinfgle sofa 7", price: "\$11.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2niu0UKjDK2USBPjmKYBnZaoremi2EK5jiQ&usqp=CAU"),
    ItemModel(name: "Sinfgle sofa 8", price: "\$19.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_glPeXVdXvW05XxrmIBIFbjy7sVAoZe3rPQ&usqp=CAU"),
    ItemModel(name: "Sinfgle sofa 9", price: "\$22.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrwA3NLQh2ev8vHMDZUyiVdgIUSsKkVvzpCg&usqp=CAU"),
    ItemModel(name: "chair 1", price: "\$10.65", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI3g8BMGdM-GX4TL3DalaFF6fUq3-74lcitw&usqp=CAU"),
    ItemModel(name: "chair 2", price: "\$11.45", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4v7cshDH6XVMwMM8lxNfM2IDbCm2p-HcU0A&usqp=CAU"),
    ItemModel(name: "chair 3", price: "\$9.34", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT061KbyLkzQl9kLhCfUY_zomAKc7aw8Q5aTA&usqp=CAU"),
    ItemModel(name: "chair 4", price: "\$32.21", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI3g8BMGdM-GX4TL3DalaFF6fUq3-74lcitw&usqp=CAU"),
    ItemModel(name: "chair 5", price: "\$22.89", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMTaXaAaP1yoyPUSa-idDcrdlisr3hKNHvWg&usqp=CAU"),
    ItemModel(name: "chair 6", price: "\$32.87", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfUWM9UXodLCmeQciWzJwOO0sy-ehtIx7X_uM9OMei_DygcQJQZ826k_V2oLYxpuMTz40&usqp=CAU"),
    ItemModel(name: "chair 7", price: "\$12.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToSs3LR1GY40hFClf35hPFxz8iB4_FkvFvHQ&usqp=CAU"),
    ItemModel(name: "chair 8", price: "\$13.35", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRt1y2xjQ_W7zp1vpYDyxLDdL_N0Ih6JOUvUQ&usqp=CAU"),
    ItemModel(name: "chair 9", price: "\$14.78", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMSTYwc4lNC_TJJ1Y7Qx5C2Jkr6Wl5aQ0MHg&usqp=CAU"),
    ItemModel(name: "chair 10", price: "\$23.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs6YkvFDKN7Q4_N9JHWyWxMT3CqUFsV-jrxQ&usqp=CAU"),
    ItemModel(name: "chair 11", price: "\$33.32", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9O1r4DHrKCiTkDmII0gFOXvb-lNXB-GaQNA&usqp=CAU"),
    ItemModel(name: "chair 12", price: "\$41.45", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRexhy7VqVPp7y8lEoDWvMHT3jpuquntBIOUg&usqp=CAU"),
    ItemModel(name: "chair 13", price: "\$13.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-lmn3IrNukESQXI2y7w1pYGjCQgYlJrHN_A&usqp=CAU"),
    ItemModel(name: "chair 14", price: "\$43.54", img:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGpKCz4BZTflgv9SZOeVA2Ml6thlF8xApMZ6pq1c8yNu5s35Igp5QEtVnCna5OrlF3tKc&usqp=CAU"),
    ItemModel(name: "Book Shelf 1", price: "\$987.34", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-rllXOlibfY8J0upWx97UytklfgnV9cfluQ&usqp=CAU"),
    ItemModel(name: "Book Shelf 2", price: "\$654.65", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSB_IUyCiAne0UuMBDI1tpJCNtFyw1nL9zAvw&usqp=CAU"),
    ItemModel(name: "Book Shelf 3", price: "\$345.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwc9OYsaVzfUUno8ujuk0NQL572AUhZKTvww&usqp=CAU"),
    ItemModel(name: "Book Shelf 4", price: "\$753.77", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLwDOqTAxMnJQqYwhZBCZXIb_6ooCPeGcItg&usqp=CAU"),
    ItemModel(name: "Book Shelf 5", price: "\$345.97", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMKsZJflvdS-Bb-n7kEzIVC4Q2XXuWBZoP9Q&usqp=CAU"),
    ItemModel(name: "Book Shelf 6", price: "\$765.43", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP0L7oNPfxTLAFzBr_ioY-NqAfcqvBzXspBA&usqp=CAU"),
    ItemModel(name: "Book Shelf 7", price: "\$977.47", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZKJnY768iZ04MLroyEEA2BIuIAsTvvlU9Gg&usqp=CAU"),
    ItemModel(name: "Book Shelf 8", price: "\$323.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwlOWk9RWtiw_acUt2SWNRcRZvEMbV5C0-eA&usqp=CAU"),
    ItemModel(name: "Book Shelf 9", price: "\$423.54", img: "https://image.made-in-china.com/202f0j00yEIGAjDrAFpM/Modern-Wooden-Bookcase-with-Study-Table-Set-Computer-Desk-Customized.webp"),
    ItemModel(name: "Study Table 1", price: "\$234.09", img: "https://m.media-amazon.com/images/I/71EYrMjWDlL._AC_UF894,1000_QL80_DpWeblab_.jpg"),
    ItemModel(name: "Study Table 2", price: "\$268.12", img: "https://mrnanyang.com/cdn/shop/products/Screenshot2023-01-14113830.png?v=1673668495"),
    ItemModel(name: "Study Table 3", price: "\$321.16", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQE2cyZU4OZbkrDg7OKk4jqlj1nbjLaJKFEPkBjmS1MYxiVg28gKwuh6spnFF23z1n2CRg&usqp=CAU"),
    ItemModel(name: "Study Table 4", price: "\$298.90", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPZTO573jx-bsEyDeNbd30QHSUTSQAQHLD_w&usqp=CAU"),
    ItemModel(name: "Study Table 5", price: "\$265.94", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbAM7F-LcohHlVtsF972baiPs58X5VmgDmYw&usqp=CAU"),
    ItemModel(name: "Study Table 6", price: "\$245.33", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2yWnQTr_sduYBfJnQO1gziZzoGU8mOR6N8g&usqp=CAU"),
    ItemModel(name: "Study Table 7", price: "\$217.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkkQ3QHF10j7voYLTM8XznnpFIArNqBJkloQ&usqp=CAU"),
    ItemModel(name: "Study Table 8", price: "\$277.23", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-YQ64Rzxs4RotmUFEo9pylYCbSHmcgwOPOw&usqp=CAU"),
    ItemModel(name: "Study Table 9", price: "\$202.11", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxYOWi5TgFVTkM1Ir74jm361IzKUxw_7BRuhI1F_HyXvgLvghypaMBbuaQT8L-85PGr64&usqp=CAU"),
    ItemModel(name: "Study Table 10", price: "\$294.20", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQz8_mBBcyRXPgdPRqCEKiw1hFStPvSFqUfmw&usqp=CAU"),
    ItemModel(name: "Study Table 11", price: "\$300.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhzVLd3TbKAzRTb4Rx31k7Wo5493IVsP3S_Q&usqp=CAU"),
    ItemModel(name: "Study Table 12", price: "\$211.28", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlgu2rbWgCovL7E2xTx11qQ5xQa9ru1ItK5Q&usqp=CAU"),
    ItemModel(name: "Study Table 13", price: "\$222.19", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUmqzHwhvtwEhwctexFew-k-r9iPQU9EaWLQ&usqp=CAU"),
    ItemModel(name: "Study Table 14", price: "\$276.12", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3R5PDUpGxCmy3D8zIGoYvgEQ_-lI3sUiFDA&usqp=CAU"),
    ItemModel(name: "Study Table 15", price: "\$256.12", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRIAIwkB6HZlfbVC1-zmh4V_1KmcfCx5RVTe3U1zJilVbrtGsmL3vKQuptnpE8YTwYKmg&usqp=CAU"),
    ItemModel(name: "Study Table 1", price: "\$234.09", img: "https://m.media-amazon.com/images/I/71EYrMjWDlL._AC_UF894,1000_QL80_DpWeblab_.jpg"),
    ItemModel(name: "Study Table 2", price: "\$268.12", img: "https://mrnanyang.com/cdn/shop/products/Screenshot2023-01-14113830.png?v=1673668495"),
    ItemModel(name: "Study Table 3", price: "\$321.16", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQE2cyZU4OZbkrDg7OKk4jqlj1nbjLaJKFEPkBjmS1MYxiVg28gKwuh6spnFF23z1n2CRg&usqp=CAU"),
    ItemModel(name: "Study Table 4", price: "\$298.90", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPZTO573jx-bsEyDeNbd30QHSUTSQAQHLD_w&usqp=CAU"),
    ItemModel(name: "Study Table 5", price: "\$265.94", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbAM7F-LcohHlVtsF972baiPs58X5VmgDmYw&usqp=CAU"),
    ItemModel(name: "Study Table 6", price: "\$245.33", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2yWnQTr_sduYBfJnQO1gziZzoGU8mOR6N8g&usqp=CAU"),
    ItemModel(name: "Study Table 7", price: "\$217.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkkQ3QHF10j7voYLTM8XznnpFIArNqBJkloQ&usqp=CAU"),
    ItemModel(name: "Study Table 8", price: "\$277.23", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-YQ64Rzxs4RotmUFEo9pylYCbSHmcgwOPOw&usqp=CAU"),
    ItemModel(name: "Study Table 9", price: "\$202.11", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxYOWi5TgFVTkM1Ir74jm361IzKUxw_7BRuhI1F_HyXvgLvghypaMBbuaQT8L-85PGr64&usqp=CAU"),
    ItemModel(name: "Study Table 10", price: "\$294.20", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQz8_mBBcyRXPgdPRqCEKiw1hFStPvSFqUfmw&usqp=CAU"),
    ItemModel(name: "Study Table 11", price: "\$300.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhzVLd3TbKAzRTb4Rx31k7Wo5493IVsP3S_Q&usqp=CAU"),
    ItemModel(name: "Study Table 12", price: "\$211.28", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlgu2rbWgCovL7E2xTx11qQ5xQa9ru1ItK5Q&usqp=CAU"),
    ItemModel(name: "Study Table 13", price: "\$222.19", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUmqzHwhvtwEhwctexFew-k-r9iPQU9EaWLQ&usqp=CAU"),
    ItemModel(name: "Study Table 14", price: "\$276.12", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3R5PDUpGxCmy3D8zIGoYvgEQ_-lI3sUiFDA&usqp=CAU"),
    ItemModel(name: "Study Table 15", price: "\$256.12", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRIAIwkB6HZlfbVC1-zmh4V_1KmcfCx5RVTe3U1zJilVbrtGsmL3vKQuptnpE8YTwYKmg&usqp=CAU"),
    ItemModel(name: "Bed 1", price: "\$598.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYKs7PbeM3FSsBlyvrCUcjqhk-zigT5J9iTA&usqp=CAU"),
    ItemModel(name: "Bed 2", price: "\$687.67", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCJFpIKXRgCuc8oi944jHVqx0TbrR10nejog&usqp=CAU"),
    ItemModel(name: "Bed 3", price: "\$876.53", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlNmqdEaZkDUfua88D-vGw5bj6fHivHcdCTQ&usqp=CAU"),
    ItemModel(name: "Bed 4", price: "\$555.98", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgapTWhmcf7po9pb_QTp5A4jpozuAIXV1Gcw&usqp=CAU"),
    ItemModel(name: "Bed 5", price: "\$657.80", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsAPxzvVqoedZ3HCQYvhJUR3i3b4lBsPezWQ&usqp=CAU"),
    ItemModel(name: "Bed 6", price: "\$999.73", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtEM_DWmrCUJgvDdu561C-T4DRe0J2Q25HT5Ugy7T8PnJFh5co8N6MzXNe9Wy5_IPRhEI&usqp=CAU"),
    ItemModel(name: "Bed 7", price: "\$879.02", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1N_AssZTvk9ks1YeN_u3opyYYSLpvBVX05pbGZ7f9J_5Kfqn-KAxSuXSOBThjLQ_b-qw&usqp=CAU"),
    ItemModel(name: "Bed 8", price: "\$799.17", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHNDYiiVJKMxZo6hf49L3VoDon5sGOxMqr6A&usqp=CAU"),
    ItemModel(name: "Bed 9", price: "\$678.11", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-dPUjyyg5wxbyRU_ygF5x_g5072fkTDZB8w&usqp=CAU"),
    ItemModel(name: "Bed 10", price: "\$907.00", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1yzL-b86nehgYo7QC-Qax54CGjOUoAWJG2g&usqp=CAU"),
    ItemModel(name: "Bed 11", price: "\$609.50", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRz1L1B9iPwv9TCYmySpupmTF8cwX4PkaO_2w&usqp=CAU"),
    ItemModel(name: "Table 1", price: "\$167.10", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKa8uTG4QKBGtuaIp0cXxRfB9qWcqvCpmIkw&usqp=CAU"),
    ItemModel(name: "Table 2", price: "\$198.78", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP8yinlPi6D_O3ltusqNlHuHBUul-FEscznw&usqp=CAU"),
    ItemModel(name: "Table 3", price: "\$143.37", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9Ubud0EuW39eH6-TIpOaH8efB3YurG84Rrw&usqp=CAU"),
    ItemModel(name: "Table 4", price: "\$167.92", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQF9yoQQSgQssHnDt0S_Rk0J-LHPiChuFmmzw&usqp=CAU"),
    ItemModel(name: "Table 5", price: "\$195.39", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXvWVlcWIsB_kbTj5tHkeCl5bKgVcobxLjyw&usqp=CAU"),
    ItemModel(name: "Table 6", price: "\$150.33", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVGLDrXJmyiWflMr9sSs2K6TFJ3Y-pDXeZcQ&usqp=CAU"),
    ItemModel(name: "Table 7", price: "\$176.00", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRE0jfE2GNwznBBcXCDtb_zN20TOx8eW-OCa9gH1tcVbAbGVYQp9r737KNuFZ_F_iSOU_8&usqp=CAU")];
    
  static List<ItemModel> sofasetList=[
    ItemModel(name: "sofa set 1", price: "\$1000", img: "https://shop.gkwretail.com/cdn/shop/articles/Sofa_design.jpg?v=1673875085&width=1100"),
    ItemModel(name: "sofa set 2", price: "\$765.9", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRclYTJ5hnMLqzF3Ah6rfAzcyDEabZfpbLpoA&usqp=CAU"),
    ItemModel(name: "sofa set 3", price: "\$43.4", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN-LhGyTbSV2vUKnrLViVQCzLo1N1_O04arA&usqp=CAU"),
    ItemModel(name: "sofa set 4", price: "\$345.56", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQac97KyilTr7wQE4BgIcmneXGtEOad5Zbt9rP6vxdxjkI9S6S2wT5KkneDgs5Pe0gKKY4&usqp=CAU"),
    ItemModel(name: "sofa set 5", price: "\$643.7", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmJmQkjLI5d9mij3K7VR3wSyTaSdOTCBqU7g&usqp=CAU"),
    ItemModel(name: "sofa set 6", price: "\$345.1", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_OQJ6Vl1dXiR6x5bn0jzCJJ1eXgZtkxl5Zg&usqp=CAU"),
    ItemModel(name: "sofa set 7", price: "\$765.55", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRQs8xETKdDw_UnRQxUFg3cq96Q9j6YxzNZA&usqp=CAU"),
    ItemModel(name: "sofa set 8", price: "\$234.98", img: "https://images.sofology.co.uk/c_scale,w_460,q_70,dpr_3,fl_lossy,f_auto/productmedia/lifestyle/sku001032404.jpg"),
    ItemModel(name: "sofa set 9", price: "\$532.66", img: "https://medleyhome.com/cdn/shop/collections/medley-sofas-collection.jpg?v=1673566513&width=2048")];

  static List<ItemModel> singlesofaList=[
    ItemModel(name: "Sinfgle sofa 1", price: "\$23.99", img: "https://urbangalleria.com/cdn/shop/products/hester-sofa-set.jpg?v=1664456482"),
    ItemModel(name: "Sinfgle sofa 2", price: "\$12.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFhd3cqiuUS0zdgN8RNkgvy3zXMLj1mSWIdA&usqp=CAU"),
    ItemModel(name: "Sinfgle sofa 3", price: "\$43.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBRH5JsZ23C35nHBQD_ALzErYZGmX9im_f7w&usqp=CAU"),
    ItemModel(name: "Sinfgle sofa 4", price: "\$13.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrUsMEehCr_8P2SxjckpU0XawJsvZK4VDIVA&usqp=CAU"),
    ItemModel(name: "Sinfgle sofa 5", price: "\$18.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_MAJ4uT9QpZ4RBgknoEC4h3bYP35z-T3JIg&usqp=CAU"),
    ItemModel(name: "Sinfgle sofa 6", price: "\$16.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsUxShGRXdk-Sm-ESIWE8UgmjmL9ErkGwAkA&usqp=CAU"),
    ItemModel(name: "Sinfgle sofa 7", price: "\$11.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2niu0UKjDK2USBPjmKYBnZaoremi2EK5jiQ&usqp=CAU"),
    ItemModel(name: "Sinfgle sofa 8", price: "\$19.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_glPeXVdXvW05XxrmIBIFbjy7sVAoZe3rPQ&usqp=CAU"),
    ItemModel(name: "Sinfgle sofa 9", price: "\$22.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrwA3NLQh2ev8vHMDZUyiVdgIUSsKkVvzpCg&usqp=CAU")];

  static List<ItemModel> chairsList=[
    ItemModel(name: "chair 1", price: "\$10.65", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI3g8BMGdM-GX4TL3DalaFF6fUq3-74lcitw&usqp=CAU"),
    ItemModel(name: "chair 2", price: "\$11.45", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4v7cshDH6XVMwMM8lxNfM2IDbCm2p-HcU0A&usqp=CAU"),
    ItemModel(name: "chair 3", price: "\$9.34", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT061KbyLkzQl9kLhCfUY_zomAKc7aw8Q5aTA&usqp=CAU"),
    ItemModel(name: "chair 4", price: "\$32.21", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI3g8BMGdM-GX4TL3DalaFF6fUq3-74lcitw&usqp=CAU"),
    ItemModel(name: "chair 5", price: "\$22.89", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMTaXaAaP1yoyPUSa-idDcrdlisr3hKNHvWg&usqp=CAU"),
    ItemModel(name: "chair 6", price: "\$32.87", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfUWM9UXodLCmeQciWzJwOO0sy-ehtIx7X_uM9OMei_DygcQJQZ826k_V2oLYxpuMTz40&usqp=CAU"),
    ItemModel(name: "chair 7", price: "\$12.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToSs3LR1GY40hFClf35hPFxz8iB4_FkvFvHQ&usqp=CAU"),
    ItemModel(name: "chair 8", price: "\$13.35", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRt1y2xjQ_W7zp1vpYDyxLDdL_N0Ih6JOUvUQ&usqp=CAU"),
    ItemModel(name: "chair 9", price: "\$14.78", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMSTYwc4lNC_TJJ1Y7Qx5C2Jkr6Wl5aQ0MHg&usqp=CAU"),
    ItemModel(name: "chair 10", price: "\$23.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs6YkvFDKN7Q4_N9JHWyWxMT3CqUFsV-jrxQ&usqp=CAU"),
    ItemModel(name: "chair 11", price: "\$33.32", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9O1r4DHrKCiTkDmII0gFOXvb-lNXB-GaQNA&usqp=CAU"),
    ItemModel(name: "chair 12", price: "\$41.45", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRexhy7VqVPp7y8lEoDWvMHT3jpuquntBIOUg&usqp=CAU"),
    ItemModel(name: "chair 13", price: "\$13.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-lmn3IrNukESQXI2y7w1pYGjCQgYlJrHN_A&usqp=CAU"),
    ItemModel(name: "chair 14", price: "\$43.54", img:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGpKCz4BZTflgv9SZOeVA2Ml6thlF8xApMZ6pq1c8yNu5s35Igp5QEtVnCna5OrlF3tKc&usqp=CAU")];
      
  static List<ItemModel> bookShelfList=[
    ItemModel(name: "Book Shelf 1", price: "\$987.34", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-rllXOlibfY8J0upWx97UytklfgnV9cfluQ&usqp=CAU"),
    ItemModel(name: "Book Shelf 2", price: "\$654.65", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSB_IUyCiAne0UuMBDI1tpJCNtFyw1nL9zAvw&usqp=CAU"),
    ItemModel(name: "Book Shelf 3", price: "\$345.99", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwc9OYsaVzfUUno8ujuk0NQL572AUhZKTvww&usqp=CAU"),
    ItemModel(name: "Book Shelf 4", price: "\$753.77", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLwDOqTAxMnJQqYwhZBCZXIb_6ooCPeGcItg&usqp=CAU"),
    ItemModel(name: "Book Shelf 5", price: "\$345.97", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMKsZJflvdS-Bb-n7kEzIVC4Q2XXuWBZoP9Q&usqp=CAU"),
    ItemModel(name: "Book Shelf 6", price: "\$765.43", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP0L7oNPfxTLAFzBr_ioY-NqAfcqvBzXspBA&usqp=CAU"),
    ItemModel(name: "Book Shelf 7", price: "\$977.47", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZKJnY768iZ04MLroyEEA2BIuIAsTvvlU9Gg&usqp=CAU"),
    ItemModel(name: "Book Shelf 8", price: "\$323.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwlOWk9RWtiw_acUt2SWNRcRZvEMbV5C0-eA&usqp=CAU"),
    ItemModel(name: "Book Shelf 9", price: "\$423.54", img: "https://image.made-in-china.com/202f0j00yEIGAjDrAFpM/Modern-Wooden-Bookcase-with-Study-Table-Set-Computer-Desk-Customized.webp")];

  static List<ItemModel> studyTableList=[
    ItemModel(name: "Study Table 1", price: "\$234.09", img: "https://m.media-amazon.com/images/I/71EYrMjWDlL._AC_UF894,1000_QL80_DpWeblab_.jpg"),
    ItemModel(name: "Study Table 2", price: "\$268.12", img: "https://mrnanyang.com/cdn/shop/products/Screenshot2023-01-14113830.png?v=1673668495"),
    ItemModel(name: "Study Table 3", price: "\$321.16", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQE2cyZU4OZbkrDg7OKk4jqlj1nbjLaJKFEPkBjmS1MYxiVg28gKwuh6spnFF23z1n2CRg&usqp=CAU"),
    ItemModel(name: "Study Table 4", price: "\$298.90", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPZTO573jx-bsEyDeNbd30QHSUTSQAQHLD_w&usqp=CAU"),
    ItemModel(name: "Study Table 5", price: "\$265.94", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbAM7F-LcohHlVtsF972baiPs58X5VmgDmYw&usqp=CAU"),
    ItemModel(name: "Study Table 6", price: "\$245.33", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2yWnQTr_sduYBfJnQO1gziZzoGU8mOR6N8g&usqp=CAU"),
    ItemModel(name: "Study Table 7", price: "\$217.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkkQ3QHF10j7voYLTM8XznnpFIArNqBJkloQ&usqp=CAU"),
    ItemModel(name: "Study Table 8", price: "\$277.23", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-YQ64Rzxs4RotmUFEo9pylYCbSHmcgwOPOw&usqp=CAU"),
    ItemModel(name: "Study Table 9", price: "\$202.11", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxYOWi5TgFVTkM1Ir74jm361IzKUxw_7BRuhI1F_HyXvgLvghypaMBbuaQT8L-85PGr64&usqp=CAU"),
    ItemModel(name: "Study Table 10", price: "\$294.20", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQz8_mBBcyRXPgdPRqCEKiw1hFStPvSFqUfmw&usqp=CAU"),
    ItemModel(name: "Study Table 11", price: "\$300.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhzVLd3TbKAzRTb4Rx31k7Wo5493IVsP3S_Q&usqp=CAU"),
    ItemModel(name: "Study Table 12", price: "\$211.28", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlgu2rbWgCovL7E2xTx11qQ5xQa9ru1ItK5Q&usqp=CAU"),
    ItemModel(name: "Study Table 13", price: "\$222.19", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUmqzHwhvtwEhwctexFew-k-r9iPQU9EaWLQ&usqp=CAU"),
    ItemModel(name: "Study Table 14", price: "\$276.12", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3R5PDUpGxCmy3D8zIGoYvgEQ_-lI3sUiFDA&usqp=CAU"),
    ItemModel(name: "Study Table 15", price: "\$256.12", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRIAIwkB6HZlfbVC1-zmh4V_1KmcfCx5RVTe3U1zJilVbrtGsmL3vKQuptnpE8YTwYKmg&usqp=CAU")];

  static List<ItemModel> bedList=[
    ItemModel(name: "Bed 1", price: "\$598.54", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYKs7PbeM3FSsBlyvrCUcjqhk-zigT5J9iTA&usqp=CAU"),
    ItemModel(name: "Bed 2", price: "\$687.67", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCJFpIKXRgCuc8oi944jHVqx0TbrR10nejog&usqp=CAU"),
    ItemModel(name: "Bed 3", price: "\$876.53", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlNmqdEaZkDUfua88D-vGw5bj6fHivHcdCTQ&usqp=CAU"),
    ItemModel(name: "Bed 4", price: "\$555.98", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgapTWhmcf7po9pb_QTp5A4jpozuAIXV1Gcw&usqp=CAU"),
    ItemModel(name: "Bed 5", price: "\$657.80", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsAPxzvVqoedZ3HCQYvhJUR3i3b4lBsPezWQ&usqp=CAU"),
    ItemModel(name: "Bed 6", price: "\$999.73", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtEM_DWmrCUJgvDdu561C-T4DRe0J2Q25HT5Ugy7T8PnJFh5co8N6MzXNe9Wy5_IPRhEI&usqp=CAU"),
    ItemModel(name: "Bed 7", price: "\$879.02", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1N_AssZTvk9ks1YeN_u3opyYYSLpvBVX05pbGZ7f9J_5Kfqn-KAxSuXSOBThjLQ_b-qw&usqp=CAU"),
    ItemModel(name: "Bed 8", price: "\$799.17", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHNDYiiVJKMxZo6hf49L3VoDon5sGOxMqr6A&usqp=CAU"),
    ItemModel(name: "Bed 9", price: "\$678.11", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-dPUjyyg5wxbyRU_ygF5x_g5072fkTDZB8w&usqp=CAU"),
    ItemModel(name: "Bed 10", price: "\$907.00", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1yzL-b86nehgYo7QC-Qax54CGjOUoAWJG2g&usqp=CAU"),
    ItemModel(name: "Bed 11", price: "\$609.50", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRz1L1B9iPwv9TCYmySpupmTF8cwX4PkaO_2w&usqp=CAU")];

  static List<ItemModel> tableList=[
    ItemModel(name: "Table 1", price: "\$167.10", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKa8uTG4QKBGtuaIp0cXxRfB9qWcqvCpmIkw&usqp=CAU"),
    ItemModel(name: "Table 2", price: "\$198.78", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP8yinlPi6D_O3ltusqNlHuHBUul-FEscznw&usqp=CAU"),
    ItemModel(name: "Table 3", price: "\$143.37", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9Ubud0EuW39eH6-TIpOaH8efB3YurG84Rrw&usqp=CAU"),
    ItemModel(name: "Table 4", price: "\$167.92", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQF9yoQQSgQssHnDt0S_Rk0J-LHPiChuFmmzw&usqp=CAU"),
    ItemModel(name: "Table 5", price: "\$195.39", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXvWVlcWIsB_kbTj5tHkeCl5bKgVcobxLjyw&usqp=CAU"),
    ItemModel(name: "Table 6", price: "\$150.33", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVGLDrXJmyiWflMr9sSs2K6TFJ3Y-pDXeZcQ&usqp=CAU"),
    ItemModel(name: "Table 7", price: "\$176.00", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRE0jfE2GNwznBBcXCDtb_zN20TOx8eW-OCa9gH1tcVbAbGVYQp9r737KNuFZ_F_iSOU_8&usqp=CAU")];
}


